import { theme } from 'src/constant/Theme'

export const customStyles = {
  stepIndicatorSize: 25,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: theme.colors.secondary,
  stepStrokeWidth: 3,
  stepStrokeFinishedColor: theme.colors.secondary,
  stepStrokeUnFinishedColor: theme.colors.grey3,
  separatorFinishedColor: theme.colors.secondary,
  separatorUnFinishedColor: theme.colors.grey3,
  stepIndicatorFinishedColor: theme.colors.secondary,
  stepIndicatorUnFinishedColor: theme.colors.white,
  stepIndicatorCurrentColor: theme.colors.white,
  stepIndicatorLabelFontSize: 13,
  currentStepIndicatorLabelFontSize: 13,
  stepIndicatorLabelCurrentColor: theme.colors.secondary,
  stepIndicatorLabelFinishedColor: theme.colors.white,
  stepIndicatorLabelUnFinishedColor: theme.colors.grey3,
  labelColor: theme.colors.grey4,
  labelSize: 13,
  currentStepLabelColor: theme.colors.secondary,
}
